name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1.0.1
      
    - name: Setup VSTest Path
      uses: darenm/Setup-VSTest@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      
    - name: Restore NuGet
      run: nuget restore FolderZipper\FolderZipper.sln /p:Configuration=Release
      
    - name: Build
      run: msbuild FolderZipper\FolderZipper.sln /p:RestorePackages=false /p:Configuration=Release

    - name: Test
      run: vstest.console.exe /Platform:x64 .\FolderZipperTest\FolderZipperTest.csproj --no-build --verbosity normal -f ".NETFramework,Version=v4.8"
