name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 4.8.x
    - name: Build
      run: dotnet build FolderZipper\FolderZipper.sln -c Release
    - name: Test
      run: dotnet test .\FolderZipperTest\FolderZipperTest.csproj --no-build --verbosity normal
