name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x
    - name: Restore NuGet
      run: nuget restore FolderZipper\FolderZipper.sln
    - name: Build
      run: dotnet build FolderZipper\FolderZipper.sln -c Release
    - name: Test
      run: dotnet test .\FolderZipperTest\FolderZipperTest.csproj --no-build --verbosity normal
