name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore FolderZipper\FolderZipper.sln
    - name: Build
      run: dotnet build FolderZipper\FolderZipper.sln --no-restore -c Release
    - name: Test
      run: dotnet test .\FolderZipperTest\FolderZipperTest.csproj --no-build --verbosity normal
