name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup NuGet Action
      uses: NuGet/setup-nuget@v1.0.2
      
    - name: Setup MSBuild Action
      uses: microsoft/setup-msbuild@v1.0.1
      
    - name: Setup VSTest Action
      uses: darenm/Setup-VSTest@v1

    - name: Restore FolderZipper
      run: nuget restore -SolutionDirectory .
      
    - name: Build
      run: msbuild .\FolderZipper.sln /p:RestorePackages=false /p:Configuration=Release

    - name: Test
      run: vstest.console.exe .\FolderZipperTest\FolderZipperTest.csproj /Parallel /Enablecodecoverage /Framework:".NETFramework,Version=v4.8" /Platform:x64
